### ISSUE TITLE
左侧边栏貌似不能高度自适应

### ISSUE THREAD

**Issue by numbcoder** [mapleobserver/FarBox-Template-GreyshadeM#1]
首先感谢你做了这个主题，我很喜欢！

有几个小细节我觉得可以稍微改进一下：
1. 左边栏高度貌似不能自适应，浏览器高度不够时，下面显示不出来
2. 社交图标貌似可以换成 FontAwesome，更清晰一些

**Comment by mapleobserver** [comment]
谢谢你对该主题的认可！
对两个问题的回答：
1.不是不能自适应，而是左侧边栏是不随垂直滚动条的滑动而滑动，这个是沿袭了原模板的 CSS 样式， position 属性使用了"fixed"，修改后又会导致小窗口（或者手机屏幕）时侧边栏无法正常显示，由于我的 CSS 水平较渣，暂时没想到比较好的解决方案。
2.社交图标因为没有国内社交网站没有 FontAwesome ，加上想尽量让用户自定义，所以也是沿用了原模板的实现方式。此处设定了让用户可以自己添加图标，就是为了方便用户添加自己满意的图片，我给的图标压缩包只是当时自己草草收集的图标。
